---
- name: Install sslh
  apt:
    package: sslh
    install_recommends: false
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10

- name: Generate the sslh port multiplexer systemd defaults file
  template:
    src: sslh.default.j2
    dest: /etc/default/sslh
  notify: Restart sslh

- name: Generate the sslh port multiplexer config file
  template:
    src: sslh.cfg.j2
    dest: /etc/sslh.cfg
  notify: Restart sslh

- name: Create the sslh systemd drop-in configuration directory
  file:
    path: "{{ sslh_systemd_service_path }}"
    state: directory

- name: Generate the sslh systemd drop-in service file
  template:
    src: sslh.service.j2
    dest: "{{ sslh_systemd_service_path }}/10-restart-failure.conf"
    mode: 0644

- name: Enable the sslh service
  systemd:
    daemon_reload: true
    name: sslh.service
    enabled: true
    state: restarted
