---
- block:
    - name: Apply custom sysctl values
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        ignoreerrors: true
        sysctl_set: true
        reload: true
        state: present
      with_items: "{{ sysctl_values }}"
  when: ansible_virtualization_type != 'lxc'
