---
ocserv_ca_cn: "Streisand"
ocserv_ca_organization: "Streisand Effect Automated Signing, Inc."
ocserv_port: "4443"
ocserv_server_organization: "Streisand Effect Servers, Inc."
ocserv_key_ou: "nogroup"
streisand_mirror_warning: "One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue."
streisand_mirror_warning_seconds: "20"
