---
stunnel_days_valid: "1825"
stunnel_request_subject: "/C={{ stunnel_cert_country }}/ST={{ stunnel_cert_province }}/L={{ stunnel_cert_city }}/O={{ stunnel_cert_org }}/OU={{ stunnel_cert_ou }}"
stunnel_path: "/etc/stunnel"
stunnel_cert: "{{ stunnel_path }}/stunnel.crt"
stunnel_key: "{{ stunnel_path }}/stunnel.key"
stunnel_pkcs12: "{{ openvpn_gateway_location }}/stunnel.p12"
