---
# Import the GPG playbook vars
- name: Loading GPG variables
  include_vars: "../../gpg/vars/main.yml"

- name: "Download the {{ project_name }} files"
  get_url:
    url: "{{ project_download_baseurl }}/{{ item.file }}"
    dest: "{{ project_download_location }}/{{ item.file }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ project_download_files }}"

- name: "Download the {{ project_name }} signatures"
  get_url:
    url: "{{ project_download_baseurl }}/{{ item.sig }}"
    dest: "{{ project_download_location }}/{{ item.sig }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ project_download_files }}"

- name: >
    "Verify the {{ project_name }} download signatures with the Streisand
    GPG keyring" # noqa no-changed-when
  command: "gpgv2 --keyring {{ streisand_gpg_keyring }} {{ project_download_location }}/{{ item.sig }} {{ project_download_location }}/{{ item.file }}"
  environment:
    # We need to explicitly override the configured LANG, LC_MESSAGES and LC_ALL
    # env vars to ensure that we can match on English output even on systems
    # that have a non-english locale configured. It's _probably_ enough to
    # override just LANG but it sounds like there are some cases where LC_ALL
    # takes precedence and setting env vars is cheap!
    LANG: "en_US.UTF-8"
    LC_MESSAGES: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
  register: gpg_verification_results
  with_items: "{{ project_download_files }}"

- name: "Verify the {{ project_name }} download signature checks all passed"
  assert:
    that:
      - "not item.failed"
      - "item.rc == 0"
    msg: "Verifying {{ item.item.file }} GPG signature failed!!"
  with_items: "{{ gpg_verification_results.results }}"
  loop_control:
    label: "{{ item.item.file }}"
    no_log: true
