---
# SSH Client Download variables
# -----------------------------
ssh_mirror_location: "{{ streisand_mirror_location }}/ssh"
ssh_mirror_href_base: "/mirror/ssh"

putty_base_download_url: "https://the.earth.li/~sgtatham/putty/latest/w32"

putty_filename: "putty.exe"
putty_sig_filename: "{{ putty_filename }}.gpg"
putty_href: "{{ ssh_mirror_href_base }}/{{ putty_filename }}"
# download-and-verify.yml renames files with non-standard extensions
putty_sig_href: "{{ ssh_mirror_href_base }}/{{ putty_filename }}.asc"

putty_download_files:
  - { "file": "{{ putty_filename }}", "sig": "{{ putty_sig_filename }}" }

sshuttle_version: "1.1.0"
sshuttle_filename: "sshuttle-{{ sshuttle_version }}.tar.gz"
sshuttle_href: "{{ ssh_mirror_href_base }}/{{ sshuttle_filename }}"
sshuttle_url: "https://github.com/sshuttle/sshuttle/archive/refs/tags/v{{ sshuttle_version }}.tar.gz"
sshuttle_checksum: "sha256:0ed1955538abd3ff9c452ae393095c2896651ac766b351a980e335a153a61c81"
