---
- name: Install UFW
  apt:
    package: ufw
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10

- name: Disable UFW logging
  lineinfile:
    dest: /etc/ufw/ufw.conf
    regexp: "^LOGLEVEL"
    line: "LOGLEVEL=off"

- name: Change the default forward policy
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY"
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Ensure UFW allows SSH
  ufw:
    to_port: "{{ ssh_port }}"
    proto: "tcp"
    rule: "allow"

- name: Ensure UFW is enabled and denies by default
  ufw:
    state: "enabled"
    policy: "deny"
    direction: "incoming"

- name: Ensure UFW allows nginx
  ufw:
    to_port: "{{ web_port }}"
    proto: "tcp"
    rule: "allow"
